#!/bin/bash
set -eou pipefail

./0_check_dependencies.sh

./stop

./1_load_conjur_policies.sh
./2_init_conjur_cert_authority.sh
./3_create_test_app_namespace.sh
./4_store_conjur_cert.sh
./5_build_and_push_containers.sh
./6_deploy_test_app.sh
./7_retrieve_secret.sh
