#!/bin/bash
set -euo pipefail

./0_check_dependencies.sh

./stop

./1_create_test_app_namespace.sh
./2_load_conjur_policies.sh
./3_init_conjur_cert_authority.sh
./4_store_conjur_cert.sh
./5_build_and_push_containers.sh
./6_deploy_test_app.sh
./7_verify_authentication.sh
