---
kind: RoleBinding
apiVersion: v1
metadata:
  name: test-app-conjur-authenticator-role-binding
  namespace: {{ TEST_APP_PROJECT_NAME }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ CONJUR_PROJECT_NAME }}
roleRef:
  kind: ClusterRole
  name: conjur-authenticator
