---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: test-app-summon
  name: test-app-summon
spec:
  replicas: 1
  selector:
    app: test-app-summon
  template:
    metadata:
      labels:
        app: test-app-summon
    spec:
      containers:
      - image: {{ TEST_APP_DOCKER_IMAGE }}
        imagePullPolicy: Always
        name: test-app
        env:
          - name: CONJUR_MAJOR_VERSION
            value: '4'
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-follower.{{ CONJUR_PROJECT_NAME }}.svc.cluster.local/api
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      - image: cyberark/conjur-openshift-authenticator
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: https://conjur-follower.{{ CONJUR_PROJECT_NAME }}.svc.cluster.local/api
          - name: CONJUR_AUTHN_URL
            value: https://conjur-follower.{{ CONJUR_PROJECT_NAME }}.svc.cluster.local/api/authn-k8s/{{ SERVICE_ID }}
          - name: CONJUR_ACCOUNT
            value: {{ CONJUR_ACCOUNT }}
          - name: CONJUR_AUTHN_LOGIN
            value: {{ TEST_APP_PROJECT_NAME }}/*/*
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONFIG_MAP_NAME }}
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
