---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-app-conjur-authenticator-role-binding-{{ CONJUR_NAMESPACE_NAME }}
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
subjects:
  - kind: ServiceAccount
    name: conjur-cluster
    namespace: {{ CONJUR_NAMESPACE_NAME }}
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccount:{{ CONJUR_NAMESPACE_NAME }}:conjur-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-authenticator-{{ CONJUR_NAMESPACE_NAME }}
