---
kind: RoleBinding
apiVersion: v1
metadata:
  name: test-app-conjur-authenticator-role-binding
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
subjects:
  - kind: ServiceAccount
    name: conjur-cluster
    namespace: {{ CONJUR_NAMESPACE_NAME }}
roleRef:
  kind: ClusterRole
  name: conjur-authenticator
