FROM cyberark/demo-app
MAINTAINER CyberArk

#---copy summon into image---#
COPY summon-conjur /usr/local/lib/summon/
COPY summon /usr/local/bin/

#---copy secrets.yml into image---#
COPY secrets.yml /etc/secrets.yml

#---override entrypoint to wrap command with summon---#
ENTRYPOINT [ "summon", "--provider", "summon-conjur", "-f", "/etc/secrets.yml", "java", "-jar", "/app.jar"]
